name: Simple Workflow Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello World! The basic action is working."