# secrets.toml

# マスター管理者のIDとパスワード
[master_credentials]
id = "master_J"
password = "nayuhimario080707141107"

# 各施設のパスワード
[passwords]
hospital_a = "pass123"
test = "test123"
hospital_b = "Kiseki-sheet"

# Gemini API Key
GEMINI_API_KEY = "AIzaSyDXWgnYUsp3XPP6HLdW499mHjls5bOuw"

